### ISSUE TITLE
Make all coping skills available

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#102]
We want to make all of the coping skills available for students, regardless of which emotion they choose.

Some open questions:
1. In what order should the coping skills appear?
2. What will be the names/thumbnails for stretching coping skills?

**Comment by ehamner** [comment]
Here are my suggestions.

Row 1: Flower Breathing, Squeeze, Cuddle, Wand
Row 2: Dance, Jumping Jacks, Exercise or Workout [which we don't have yet], Talk to the Teacher

Row 3: the stretches. Two possible naming versions below.
    a) Floor Stretching, ???, Seated Stretching, ???
    b) Wave and Hug, Rock and Twist, Spread and Curl,  Swing and Bend

![YogaSad2_FloorStretching](https://user-images.githubusercontent.com/24419423/71032602-a9673600-20e3-11ea-9696-ad9791be0139.jpg)
![YogaHappy2_Rock](https://user-images.githubusercontent.com/24419423/71032552-948aa280-20e3-11ea-82ee-f01fc1b1c03b.jpg) 
![YogaScared2_SeatedStretching2](https://user-images.githubusercontent.com/24419423/71033030-95700400-20e4-11ea-8906-30523b38e598.jpg)
![YogaMadExcited2_Swing2](https://user-images.githubusercontent.com/24419423/71032665-cdc31280-20e3-11ea-9382-0e5ff6221429.jpg)

**Comment by lczito** [comment]
I agree with @ehamner 's order suggestion completely.

Also, I like option b for names
