### ISSUE TITLE
Move position of admin button

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#107]
This was mentioned by one the teachers during our interview.

Would it make sense to move this button to be on the left side of the header? To the left or right of the logo?

**Comment by ehamner** [comment]
Would it be enough to move the admin button left a little more and remove the "i" button from the pages that show the current kid's face? That way they would not be directly on top of each other.

**Comment by lczito** [comment]
I think that works @ehamner
