### ISSUE TITLE
app crashes when trying to open camera on the A7 tablet

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#118]
When creating a new student or editing a student, clicking on the photo area or the re-take photo link causes a crash. The screen returns to the class screen and my student is not created.

After multiple times, it told me "MindfulNest keeps stopping" in an error popup message (with options for App info and Close app).

A7 tablet (it doesn't crash on the kindle)

**Comment by ehamner** [comment]
Update: The app doesn't have camera permission. I can add it by going to app info. Then it works. So it needs to ask for camera permission as a default permission or when the camera is accessed.

**Comment by tasota** [comment]
Also included an alert dialog when permissions are not granted, notifying the user that they must be enabled to access the camera.

![Screenshot_20220810-102526_MindfulNest](https://user-images.githubusercontent.com/9115672/183926912-72628330-d2f9-4cdc-be7a-7e125eb3053c.jpg)
