### ISSUE TITLE
alphabetical order is case sensitive

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#120]
On kindle and A7

Students are alphabetized Capital letters, then lower case letters. I would have expected capitalization to be ignored.

Example: Cat  apple  gerbil

**Comment by tasota** [comment]
I was playing around with ways to make the default column info ignore case (sqlite keywords COLLATE NOCASE) but it was not behaving as I expected, so instead I just added the lower() function in the SQL calls for students and classrooms.
