### ISSUE TITLE
Can't intuitively lower keyboard on A7

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#122]
On the A7, when creating a student, there isn't a way to lower the keyboard as far as I can tell. Clicking the image space, save, etc do work, but I thought I would be able to click the background to make the keyboard go away so I could see what else was on the screen. (On the kindle the default behavior is to click the down arrow on the bottom menu but the A7 doesn't have that.)

**Comment by tasota** [comment]
sadly this is just Android nonsense :(
