### ISSUE TITLE
kindle camera roll images don't work

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#125]
Kindle: images from camera roll don't load into the app. plus once i try to load one, the folder icon doesn't re-open the camera roll.

works correctly on A7

**Comment by ehamner** [comment]
It worked when I tried to load an image I had just taken using the camera on the kindle.

**Comment by tasota** [comment]
@tasota just make sure to hide icons (folder, camera-arrows) on yes/no confirmation screen
