### ISSUE TITLE
Add a version number/commit hash to the app

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#27]
Similar to what we did for the Flutter Links app. This will help with debugging/troubleshooting issues that come up during observations.

**Comment by tasota** [comment]
See Constants.java file: `public static final DeviceConnectionHandler.HardcodedValues`
This defines either as `STATION_1` (heart) or `STATION_2` (star)

**Comment by pdille** [comment]
Hash/version was added in commit a6ea8c5 but I am leaving this open if we want to expand upon this more for noting the station, etc. I had hesitation adding that ability but perhaps my reservations are unjustified.

**Comment by tasota** [comment]
not mentioned in the issue so I'll just make another one for that. Thanks @pdille!
