### ISSUE TITLE
People are confused that recording starts automatically.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#35]
Both teachers (an I) initially thought they had to press a button to start the recording. We all pressed the stop button instead. The kids in the group I was observing seemed to do ok, but they had a teacher helping them.

Seems like it either needs a button, or a clearer visual that it's time to record.

Observed 23Jan19

**Comment by tasota** [comment]
Will implement this once #36 is done
