### ISSUE TITLE
request for audio

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#36]
Audio prompts to add:
- "Do you need more time?"
- "Press the button to record how you are feeling" (from #35)

**Comment by ehamner** [comment]
Lauren observed (pilot 1, week 8) that the audio prompt for "do you need more time?" was not playing

**Comment by tasota** [comment]
Do we know which screen this was observed from? I'm guessing one of the static coping skills. I just discovered the overlay is called here and did not play the audio. Should be fixed now.

**Comment by tasota** [comment]
resolved for PD 2
