### ISSUE TITLE
Increase speed of fast heartbeat graphic

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#41]
Katie and I both have a hard time seeing the difference in the slow hear beat and fast heart beat. We think if the fast one was double the speed it currently is, it would be better. Also her heart beats pretty fast. She thought if it was moving faster it would be closer to what her heart feels like.

**Comment by tasota** [comment]
Forgot to mention this in the issue itself but @ehamner discussed making the faster heartbeat 4x faster than slow. Currently it is only 2x

**Comment by ehamner** [comment]
Some kids today also had a hard time telling which was fast. Kayla, you can see how it looks when you speed it up. Updating the speed might be enough to make it clearer.

Another thought I had was that if the fast heart beat didn't shrink as much as the slow one, that might also make it look like it's going faster.

**Comment by mo11yj** [comment]
If you guys can send me a video of the animations, I'm happy to chime in on the recommendation if it would be helpful

**Comment by tasota** [comment]
thanks molly I will send shortly

**Comment by tasota** [comment]
https://photos.app.goo.gl/kN7JsdAwSWFxG8ri6

**Comment by mo11yj** [comment]
I'm not seeing anything in that album...do I have the right sharing prefs? Or is it still uploading?

**Comment by tasota** [comment]
Sorry about that, try now.

I think when I deleted the file on my phone it removed it from google photos as well. Maybe one day sharing video won't be so cumbersome...

**Comment by mo11yj** [comment]
Got it, thanks, I'll take a look later today

**Comment by mo11yj** [comment]
I agree that it is hard to tell the difference, and I think it would help if the fast one didn't get as small. I can mock up something to give you a sense of what I think it should feel like, but I'm traveling this week and the 12" Macbook that I travel with doesn't have (and probably can't run) my animation software. I can send you something by Monday if that isn't too late.

**Comment by kaylaleung** [comment]
I've tweaked the code so that the animation for fast heartbeat is twice as
fast as it was before and it shrinks less now. Video attached. Could make
it even more dramatic of a difference if needed.
 20190207_102349.mp4
<https://drive.google.com/file/d/12Ou-gGQ038dm5ipiDSla0afcFcV927yJ/view?usp=drive_web>

**Comment by tasota** [comment]
@mo11yj no worries! We are meeting on Monday to discuss anyways so we can update you at that point if we need any further guidance.

@kaylaleung thank you for sharing! When you get a chance could you push those changes to a remote branch? Then I can show the team in person on Friday.

**Comment by ehamner** [comment]
@kaylaleung thanks for the video. That is definitely moving in the right direction. Watching it I feel like we could slow the slow heart down even more. Maybe reduce by half? Visually I think you could tell which was fast and which was slow then. 

Only thing would be that I bet the little kids' hearts will never beat that slow. @lczito what do you think about trying to match real heart speeds vs making it visually clear which is fast and which is slow?

**Comment by lczito** [comment]
It's difficult to watch both of them at once, so I think trying to slow down the slow heart even more will be helpful. I feel like my eyes are more drawn to the slow heart because it feels like it gets bigger than the fast one.

I don't think little kids will ever pick the slow heart beat if it goes much slower though. Maybe we could almost think of the two heart beats as fast and really fast?

**Comment by lczito** [comment]
Something @pdille and I are discussing is what if it isn't heart beat, but instead is breath and it is based on how much their chest is moving? It would mean doing a different graphic, but could potentially be a more tangible or understandable sensation for the little ones

**Comment by ehamner** [comment]
@rachelleduffy I want to pull you in to this discussion too. The heartbeat question comes after they have done one of the calming exercises. In what we have observed so far, unless the teacher was helping them, the kids didn't feel their heartbeat, just said "it's fast" and picked that. So maybe they would learn with more time, but maybe there is a better way they can connect with how their body feels and reacts?

**Comment by tasota** [comment]
Thank you again @kaylaleung! We all looked at it this morning and like these changes. Marking this as done now :)

**Comment by rachelleduffy** [comment]
I'm trying to put all of this in context...the children are prompted to gauge the rate of their heart after completing an exercise activity, correct? Maybe the first question would be "do you feel your heartbeat?" with some kind of visual animation that displays how a child would find their heart beat. Then ask the question of whether it is fast or slow...again using the same visual animation of a child that just completed an aerobic activity with a fast heart beat (maybe a redden face, faster breathing, sweat) vs. a child who was passively putting their hand on their chest? This may give more context to the child versus a picture of a moving heart shape....
