### ISSUE TITLE
Add video to jumping jacks coping skill

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/preK-emotions-app#44]
I think students need the visual to help them. When a student selected it in the pilot, the teacher had to show them what to do.

**Comment by tasota** [comment]
@kaylaleung by the way for the jumping jacks activity I forgot to hide the overlay when I hastily changed the abstract class that it extended. Adding something like this in its `onCreate` method should fix that:

```
findViewById(R.id.overlayYesNo).setVisibility(View.GONE);
```

Sorry about that!

**Comment by tasota** [comment]
Also we are discussing this in the meeting right now and agreed you can ignore audio playback.

And if it isn't easy to mute a video feel free to edit the file (which you might need to do for the video format anyways).

**Comment by kaylaleung** [comment]
Where can I access video number 119 to implement?

**Comment by tasota** [comment]
@kaylaleung I can swap out the video when we merge in changes to master (since I'm going to move that video file to the Assets dir anyway), but Lauren/Emily could probably also give you access to the mindfulnest folder on Box.

**Comment by lczito** [comment]
Shared the yoga video folder
