### ISSUE TITLE
Flowers not responsive

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#45]
Here is a summary of my notes from testing the flowers this week:

- Flower (heart) was off over the weekend but not charging. Monday morning I turned it on and ran it for about 5 hours, testing it 30 times. It worked fine. I also tried some variations of going through the app in different ways, cancelling out of activities, things that happened in the classroom. Worked fine.
- I left the flower on over night, not plugged in to drain the battery.
- Tuesday I charged the flower for 8 hours 45 minutes, testing roughly hourly to see if it was responsive yet. It did not respond. I unplugged it to take it home. Plugged it back in at home (for probably 1 minute or less), tested it and it worked. Left it powered on. 3 hours later it did not respond.
- Charged all night, 12 hours 20  minutes. Not responsive. Left flower turned on but charging for 3 hours.  **Tested and it worked (twice). Continued charging with flower on. 45 minutes later, tested again and it did not respond**.
- Charged rest of the day and night with flower off. About 20 hours. Not responsive.

- Tested the other flower ("test") along a roughly similar timeline. Tuesday morning, not responsive. Charged 7 hours. Took home. Plugged in for just a moment, then tested and it worked. Left on 3 hours. Not responsive. Charged 12 hours, not responsive. Charged with some tests over next 24 hours. Tried various combinations of restarting kindle, killing app, leaving app running, turning flower on first or app first. Never responsive.

**Comment by JSchapiro** [comment]
VERY interesting. I take it you have it at home with you now? I will start digging into it on monday.

**Comment by ehamner** [comment]
Related to #46 

Testing flower breathing with the flower turned of (and not plugged in) looks the same as when it is not responding. Could be a BLE issue.

**Comment by ehamner** [comment]
I've added another option to consider for Division with Remainders. 

Dial Settings: Right dial scaled 1-12, sets the number you are dividing by. Left dial scaled 1-144. While Left / Right > 12, then Right = Right + 1.

I think that's maybe more similar to the way we are proposing to do the other arithmetic operators. The scale for both dials is fixed, but sometimes the displayed value of the right dial has to be adjusted. (Maybe there's a better equation to use than the while loop format I was using?)

**Comment by tasota** [comment]
Closing this since the flower and app have both been updated to address this
