### ISSUE TITLE
Indicator of BLE connection to manipulative(s)

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#46]
Could use a visual indicator that the app is connected to the flower (or later to other manipulatives). 

Related to #45

**Comment by tasota** [comment]
There is a screen for Flutter that indicates when the device is disconnected (screenshot below). I was imagining I could just use that on the flower screen in the top right corner.

<img width="803" alt="screen shot 2019-02-04 at 12 04 43 pm" src="https://user-images.githubusercontent.com/9115672/52224105-2e9f7e80-2875-11e9-81d6-98bb294530a1.png">

@mo11yj this asset doesn't appear to be downloadable from zeplin. could you add the asset to zeplin when you get a chance?

**Comment by mo11yj** [comment]
Uploaded: zpl.io/aRWrgZn

I don't know that we need an icon when it is connected, but I think adding this one if/when it disconnects is the right approach.

**Comment by tasota** [comment]
I agree. Just having the icon when it is disconnected makes sense. Can you add the asset in the Flutter Math section on Zeplin? Then I can use the same asset for Flutter Math and on the BLE activities for MindfulNest

**Comment by tasota** [comment]
Thank you! Sorry, I noticed that if I clicked in the right spot I could access the icon from this screen: https://app.zeplin.io/project/5b9467c8163d2c1085a06a85/screen/5c0545e66f17897930dfc49f

I have to click the icon at the right spot or else I can't see a download link on the side. Not sure if this is just an issue on the web interface.

**Comment by mo11yj** [comment]
Weird, you're right, maybe a fluke of the web interface.

**Comment by tasota** [comment]
Yeah, there's another menu on the desktop version that shows all assets for a page. Between this and the accidental creation of split sections (and no option to undo on the web), I think I will just stick to using the desktop app, lol.

Sorry and thanks again @mo11yj. I'll implement this in the code shortly.
