### ISSUE TITLE
People icon is not obvious to children.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#48]
From observations (week 3):

Boy accidentally presses the wrong person's photo. He asks "where's the X?"

We have the icon of the people (function yet to be implemented, see #38), but I wonder if we should make the design for how to go back more consistent across all screens?

**Comment by mo11yj** [comment]
Added a back button throughout student section, and changed student icon to a thumbnail of the selected user, when tapped, a drop down gives the option to switch user: zpl.io/aXPKJZM

Let me know what you think.

**Comment by tasota** [comment]
@ehamner @lczito would something like this work? I'm also wondering if the text dropdown is necessary if that's the only option when selecting the image, but I'm not sure what further confirmation from the user would look like either.

<img width="797" alt="screen shot 2019-02-25 at 11 58 21 am" src="https://user-images.githubusercontent.com/9115672/53354482-d77d4e80-38f4-11e9-9585-ed99199a24bc.png">

**Comment by ehamner** [comment]
We think it could work

**Comment by tasota** [comment]
To be implemented in #60
