### ISSUE TITLE
App did not move on to breathing prompts when child pressed the ladybug button.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#49]
From observations (week 3):
App did not move on to breathing prompts when child pressed the ladybug button.

Sequence of actions as best I was able to record them:
-Using the week 3 kindle.
-Boy started pressing the button on the flower, then began the app interaction. The flower was white when he selected his photo.
-He selected sad, and then the bear activity.
-I believe it asked if he needed more time.
-Then he did the flower activity. First he was prompted to allow BLE. I allowed it. When he got to the flower screen, the BLE error icon appeared. 
-The BLE error icon went away, but the app still did not move past the ladybug screen. The flower lit up white so I know he pressed the ladybug button.
-I switched back to the week 2 kindle after that.

Second observation which seems like the same bug:
-This time we are using the week 2 version of the app
-Boy uses the flower, but the flower gets turned off. 
-We turn the flower on. App is on the ladybug screen. He presses the ladybug button and the flower lights up white, but the app does not prompt breathing. 
-The teacher presses the X to back out of the activity. 
-Then she gets it back to the activity for him and this time it works ok.

Related to #45

**Comment by tasota** [comment]
Just checking if this issue seems resolved now with the changes we made in week 5?

**Comment by ehamner** [comment]
We haven't seen more problems but Lauren and I think we should wait 1 more week because there were so few kids at the last observation.

**Comment by tasota** [comment]
@lczito do you think it is safe to close this now?

**Comment by lczito** [comment]
Yep!
