### ISSUE TITLE
Check that BLE is on/allowed earlier

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#50]
The check for BLE happens before the app contacts the flower, but I think it could also check when the app is opened so that the teacher would see it. When it comes up in the middle of the sequence the kids don't know what to do (observed week 3). They do seem to know to ask the teacher, so it's not terrible, just could be improved by checking earlier as well.

**Comment by tasota** [comment]
That's a good point. The pop-up is also wonky on that screen and I am not sure why. It might have something to do with the fullscreen mode

**Comment by tasota** [comment]
BLE is now also requested on the first screen when app is first launched. It will only ask once then dismiss. Alternatively we could "force" them to turn it on by bringing up the pop-up every time until BLE is allowed, but I was hesitant to be that persistent.
