### ISSUE TITLE
Double check time out 

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#52]
Double check that the time out is starting to time from the end of the "are you ready to move on" prompt.

From observation (week 3):

Boy recorded a very long audio (I think it was the whole time until the recording timed out and stopped on it's own). The audio played back and then the voice asked "are you ready to move on?" but then it also asked "do you need more time?" before he can select that he wants to move on. I felt like this happened more quickly than I would have expected, but it could have just been the chaos of the room.

**Comment by tasota** [comment]
Nope, you're right. the timer starts when the activity begins, so a 20-second long audio clip would only leave about 5 seconds to respond before the overlay appears.

I'll work on this

**Comment by tasota** [comment]
b7a9556f0059c7130eb3650b2427538f98647ce4
