### ISSUE TITLE
Add talk about it on the initial how do you feel page

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/preK-emotions-app#59]
![5159008948073981186](https://user-images.githubusercontent.com/11083259/53118619-8566b280-351b-11e9-9b33-d435ef4bb3d1.jpg)

**Comment by mo11yj** [comment]
![20190224_02_student_choosefeeling](https://user-images.githubusercontent.com/25698542/53302045-25785080-3828-11e9-86d7-0df4b18ab3e0.jpg)
![20190224_02a_student_choosefeeling-start recording](https://user-images.githubusercontent.com/25698542/53302046-25785080-3828-11e9-8caa-2227ed0a18fd.jpg)
![20190224_02b_student_choosefeeling-record](https://user-images.githubusercontent.com/25698542/53302047-25785080-3828-11e9-92cb-9ec9786e2e71.jpg)
![20190224_02c_student_choosefeeling 2](https://user-images.githubusercontent.com/25698542/53302048-25785080-3828-11e9-94e9-802decf0d551.jpg)

Zeplin: 
zpl.io/awmgPLJ
zpl.io/V0qJLgK
zpl.io/a3eK1jA
zpl.io/V1NwOQE

Let me know what you think!

**Comment by lczito** [comment]
We like it!

**Comment by tasota** [comment]
will implement this updated design in #61
