### ISSUE TITLE
Implement new app flow for 'talk about it' on choose emotion screen

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#61]
See discussion on #59.

Also somewhat related to #58 since we will not show talk about it as a coping skill if this was selected.

**Comment by tasota** [comment]
(from 3/25 meeting)
- flip order so talk about it is on top and emotions are below

**Comment by tasota** [comment]
@ehamner @lczito after recording, will the recorded audio play back before the audio prompt "What feeling did you describe" plays, or will the recorded audio only play back if you hit the play button?

Also, if placing the record on top now, should the play button also go on top of the emotions or leave it as is? (screenshot below)

<img width="800" alt="Screen Shot 2019-03-26 at 7 50 40 AM" src="https://user-images.githubusercontent.com/9115672/54994962-f9bdc700-4f9b-11e9-94f7-7690aae6abb6.png">

**Comment by ehamner** [comment]
I think the audio could play back before the "what feeling did you describe" prompt.

First I thought the play button would also go on top, but then a minute later I thought it should stay on the bottom.
