### ISSUE TITLE
prepare text prompt, audio, video for Yoga coping skills

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#62]
@ehamner @lczito I wanted to create an issue on github for this so we knew who would be working on this and wouldn't have multiple people trying to do it at once. Would either of you be able to prepare these files?

Once the video capability is finished we should be able to just plug in text, audio, and video to create every yoga coping skill we will need.

**Comment by tasota** [comment]
### For each coping skill we will need
- Name of the **coping skill**
- **Emotions** that the coping skill is for
- Text prompt
- audio file to play
- video file to play (clip video as required but file extension and audio channel can be modified later)
- (optional) thumbnail for coping skill, or we can just use the same yoga thumbnail for every one

**Comment by lczito** [comment]
Yep!

**Comment by lczito** [comment]
I am putting all completed videos in the "Ready for App" folder in Box

@ehamner can you check the ones in there to see if they are okay?

**Comment by tasota** [comment]
Closing this since we finished implementing the yoga videos now for pilot 1
