### ISSUE TITLE
Prompt to put the wristband back.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#65]
Prompt to put the wristband back after yoga exercises. Audio for "Put the wristband back" should be included in the yoga prompts that Jess recorded.

Related to #64. Originally I imagined it would say to put the wristband back at the end of the yoga video. However, it could wait to see if they want to do the yoga exercise again and only prompt them to put the wristband back when they say no. @lczito and @tasota what do you think?

**Comment by tasota** [comment]
That makes sense to me. Do we also want prompts for:

- Prompting to put on the wrist band (perhaps a screen with the prompt and a button to continue, both for putting it on and putting it back)
- Prompt to stand up again (I know the "Yoga Sad" currently does not prompt this in the video; it goes straight from lying down to the heartbeat)

**Comment by lczito** [comment]
The videos should already say to put on the wrist band, but eventually we will probably want a separate prompt. The audio for doing the activity again and out the wristband back are definitely in what Jess recorded. I agree they should act as separate prompts after the video

**Comment by ehamner** [comment]
No longer relevant
