### ISSUE TITLE
The timeout on the cuddle activity should be longer.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#68]
(Observed Pilot 1, Week 8)
The timeout on the cuddle activity should be longer. Probably at least 3 times what it is.

**Comment by tasota** [comment]
Right now all the static coping skills wait 30 seconds, so we can increase cuddle to be 90 seconds. I just committed code to control/customize this.

Are there any others that should have a different timeout time?

**Comment by tasota** [comment]
resolved for PD 2
