### ISSUE TITLE
Change bear to a sheep

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#72]
We are piloting with a Jewish school. A cuddly sheep or cow would be better than a bear for the cuddle activity. (Has to do with rules of what age you should introduce non kosher animals to children.)

**Comment by mo11yj** [comment]
Full screen: zpl.io/a3eZlOd

Thumbnail: zpl.io/VYkYBym

**Comment by ehamner** [comment]
Thanks Molly!

**Comment by tasota** [comment]
de790952bfb50d51d6621db8d2c2593365f17aaa
