### ISSUE TITLE
Child's face shows up on the choose class page

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#74]
Sometimes a student face will be displayed on the choose class page.

1) pick one of the students
2) back out of the app using the kindle arrow
3) reopen the app to the class page and the student's picture will be in the upper right

**Comment by tasota** [comment]
@kaylaleung do you think you could work on this as well?

**Comment by tasota** [comment]
@ehamner points out that if we just remove/hide the student button in the "choose classroom" screen this will resolve this (as well as #75)

**Comment by kaylaleung** [comment]
Yep, I'll look into fixing it.
