### ISSUE TITLE
New icon for yoga activities

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#77]
Make a more generic stretching icon. Tree pose is very "yoga" and some strong faith based communities do not want children exposed to yoga.

(Behind the yoga videos we are currently using the jumping jacks blue background.)

**Comment by mo11yj** [comment]
Background: zpl.io/VkGNnvM

Thumbnail: zpl.io/VYkYBym

**Comment by ehamner** [comment]
Cute!

**Comment by tasota** [comment]
de790952bfb50d51d6621db8d2c2593365f17aaa
