### ISSUE TITLE
Personalized student icon not displaying for all students

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#78]
In the Room 123 demo classroom, the first two students' icons display in the top right, but student 3 and 4 only show the generic three grey people.

I'm not sure how it was working with the larger classroom from the pilot.

**Comment by tasota** [comment]
This is likely because the image was a placeholder image so looking up the imageUuid left nothing.

I will change the placeholder images to be the image that molly designed and that should resolve this.
