### ISSUE TITLE
Check-in interaction request from teachers

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#83]
For the check in version, teachers have requested a reassuring message and encouragement to tell the teacher how they are feeling. 

We think we could combine the already recorded audio, for example:
"Everyone feels sad sometimes. Talk to your teacher about how you are feeling."
"It's nice to feel happy. Talk to your teacher about how you are feeling."

The image would be a check mark below the words to show that they have done their check-in. Then it would return to the main student selection screen. @mo11yj , can you make a check mark screen/icon?

**Comment by mo11yj** [comment]
Not 100% positive I understood, did we just want to add new text and a check mark button to the "talk to the teacher" page? 

Like this?

<img width="550" alt="Screen Shot 2019-04-28 at 9 53 24 AM" src="https://user-images.githubusercontent.com/25698542/56865417-9e686580-699b-11e9-819d-081c11bfd558.png">

**Comment by tasota** [comment]
@mo11yj could you add that check mark as an asset on zeplin?

**Comment by mo11yj** [comment]
@tasota gah, every time, sorry. Updated now. https://zpl.io/br8G8DW

**Comment by tasota** [comment]
all good, thank you! 😊
