### ISSUE TITLE
[Squeeze Toy] Modify squeeze background image

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/preK-emotions-app#86]
I think it would be nice if the background used for the squeeze activity showed some land (maybe just some hills or houses, etc) at the very bottom.

The way it is right now, one has to squeeze for a bit before it is clear that the background is actually moving, since there is only blue before the first cloud appears.

Here's the current background for reference: https://zpl.io/a3RJ6dY

**Comment by pdille** [comment]
Quick poke on this, @mo11yj :-)

I think if we use the background Emily found in the pdf, remove the balloon from it and then make the planets/alien changes to it we should be good!

**Comment by lczito** [comment]
Hi @mo11yj !

We are hoping to do the professional development next week with the teachers. Can you send us the background when you have a chance?

**Comment by mo11yj** [comment]
Here are two versions:
zpl.io/a3RJ6dY
zpl.io/aRXzBZN

**Comment by pdille** [comment]
Awesome, thanks @mo11yj !! I ended up using the one with the rocket, cause you can never have too many fun things in the background. :-)
