### ISSUE TITLE
Continue squeeze activity from same point

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/preK-emotions-app#92]
For the squeeze activity, when we ask if they need more time, it might be better to go back to the balloon/space image where they were rather than restarting. 

@SamS1205 @lczito what do you think from your observations?

**Comment by pdille** [comment]
Hmm, I thought it only restarts when you get to the end and it asks if you want to go again. If the "need more time" pop-up comes it should just resume when the child says yes. If that isn't actually what happens, then I certainly consider that a bug...

**Comment by lczito** [comment]
I agree!

**Comment by pdille** [comment]
This doesn't seem to be a problem (can't reproduce), but let's keep an eye on it! :)
