### ISSUE TITLE
Add video for heartbeat post-coping

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#97]
See #67 for discussion

**Comment by tasota** [comment]
@pdille the video file `hand_on_heart.mp4` is on box (MindfulNest > dev > res-raw). The current audio on the video should be muted and the audio prompt will need to be split into 2 parts.

**Comment by pdille** [comment]
Video added and skill split into two with commit 80aea83b9cd0
