### ISSUE TITLE
Modify Share activity

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/preK-emotions-app#98]
Yesterday we discussed modifying the share activity, specifically the prompt. Right now the prompt is:

_"Happiness is nice to share. Do you see someone who could use a happy friend right now? Invite them to play with you!"_

**Comment by ehamner** [comment]
How about _"Invite a friend to play with you."_ That would be applicable to any emotion.

**Comment by lczito** [comment]
@ehamner I think that works

**Comment by tasota** [comment]
change name to "Invite a Friend"
